# Generated by Django 4.0.1 on 2022-02-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Еще не придумали', max_length=50, verbose_name='Название камня')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('extra_info', models.CharField(max_length=300, null=True, verbose_name='Доп информация о трассе')),
                ('photo', models.ImageField(null=True, upload_to='boulder_photos', verbose_name='Фото')),
                ('coords', models.URLField(help_text='Принимаются метки с гугл карт', max_length=1000, null=True, verbose_name='Ссылка на локацию трассы')),
                ('amount_of_crashpads', models.IntegerField(default=0, null=True, verbose_name='Кол-во крешпедов')),
            ],
        ),
        migrations.AlterField(
            model_name='bolted_by',
            name='name',
            field=models.CharField(default='Неизвестно', max_length=50, verbose_name='Имя пробившего маршрут'),
        ),
        migrations.AlterField(
            model_name='comf',
            name='comfort',
            field=models.IntegerField(default=5, verbose_name='Уровень комфорта от 1 до 10'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(default='Проект', max_length=10, verbose_name='Выберите сложность маршрута'),
        ),
        migrations.AlterField(
            model_name='location',
            name='additional_info',
            field=models.CharField(default='Все очевидно :)', help_text='Введите информацию по поводу парковки, источников воды итд', max_length=1000, verbose_name='Доп информация'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='Неизвестно', max_length=50, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='route',
            name='bolter',
            field=models.ManyToManyField(default='Неизвестно', to='data.Bolted_By', verbose_name='Имя пробившего'),
        ),
        migrations.AlterField(
            model_name='route',
            name='comfort',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.comf', verbose_name='Насколько комфортная трасса от 1 до 10'),
        ),
        migrations.AlterField(
            model_name='route',
            name='coords',
            field=models.URLField(help_text='Принимаются метки с гугл карт', max_length=1000, null=True, verbose_name='Ссылка на локацию трассы'),
        ),
        migrations.AlterField(
            model_name='route',
            name='extra_info',
            field=models.CharField(max_length=300, null=True, verbose_name='Доп информация о трассе'),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.grade', verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.ForeignKey(default='Неизвестно', on_delete=django.db.models.deletion.CASCADE, to='data.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(default='Еще не придумали', max_length=50, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='quickdraws',
            field=models.IntegerField(default=16, verbose_name='Количество оттяжек'),
        ),
        migrations.AlterField(
            model_name='route',
            name='rope_len',
            field=models.IntegerField(default=60, verbose_name='Необходимая длина веревки'),
        ),
        migrations.AlterField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='data.sector', verbose_name='Выберите сектор'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='location',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='data.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(default='Еще не придумали', max_length=30, verbose_name='Название сектора'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='boulder',
            name='bolter',
            field=models.ManyToManyField(default='Неизвестно', to='data.Bolted_By', verbose_name='Нашел'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='comfort',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.comf', verbose_name='Насколько комфортная трасса от 1 до 10'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='grade',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.grade', verbose_name='Сложность'),
        ),
    ]
