# Generated by Django 4.0.1 on 2022-02-03 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_boulder_alter_bolted_by_name_alter_comf_comfort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='grade',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.grade', verbose_name='Сложность'),
        ),
    ]
