# Generated by Django 4.0.1 on 2022-01-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolted_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', help_text='enter Name of bolter', max_length=50, verbose_name='Name of creator')),
            ],
        ),
        migrations.CreateModel(
            name='Comf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort', models.IntegerField(default=5, help_text='comfort level from 1 to 10', verbose_name='comfort level of bolting')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='Unknown', help_text='enter the grade of the route', max_length=10, verbose_name='route grade')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Unknown', help_text='enter the area this route belongs to', max_length=50, verbose_name='area')),
                ('additional_info', models.CharField(default='No info', help_text='add info about parking, frest water etc', max_length=1000, verbose_name='additional info')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='Unknown', help_text='sector where route is located', max_length=30, verbose_name='sector')),
                ('location', models.ForeignKey(help_text='enter the area this route belongs to', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='data.location', verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', help_text='enter name of the route', max_length=50, verbose_name='route name')),
                ('rope_len', models.IntegerField(default=60, help_text='rope length', verbose_name='Rope Length')),
                ('quickdraws', models.IntegerField(default=16, help_text='number of quickdraws', verbose_name='quickdraws')),
                ('coords', models.URLField(help_text='Paste url with pin of the route from goole maps', max_length=1000, null=True, verbose_name='Link to goole maps')),
                ('extra_info', models.CharField(help_text='additional info about the route', max_length=300, null=True)),
                ('bolter', models.ManyToManyField(default='Unknown', help_text='Choose bolter', to='data.Bolted_By', verbose_name='bolter')),
                ('comfort', models.ForeignKey(default=5, help_text='comfort level from 1 to 10', on_delete=django.db.models.deletion.SET_DEFAULT, to='data.comf', verbose_name='comfort level of bolting')),
                ('grade', models.ForeignKey(default='Unknown', help_text='enter grade', on_delete=django.db.models.deletion.SET_DEFAULT, to='data.grade', verbose_name='grade')),
                ('location', models.ForeignKey(default='Unknown', help_text='location', on_delete=django.db.models.deletion.CASCADE, to='data.location', verbose_name='Location')),
                ('sector', models.ForeignKey(default=1, help_text='sector where route is located', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='data.sector', verbose_name='sector')),
            ],
        ),
    ]
